### ISSUE TITLE
On a mobile phone - can type alphabets in the SRN box (should only be numbers)

### ISSUE THREAD

**Issue by deepansh96** [avantifellows/portal-frontend#4]
Also, in mobile phone, entering something like `lajksdalns`(10 alphabets) in the SRN box keeps the button inactive but entering something like `asdqwe12345` (10 characters, but at least one is letter) makes the button active, which should not be the case

**Comment by sudheshna-donthineni** [comment]
So, Pritam had wanted me to include letters too for future use. Should I restrict to ONLY numbers?
